modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/Glitchfiend/HoneyNHell/issues"
displayURL="https://minecraft.curseforge.com/projects/honey-n-hell"
authors="Adubbz, Forstride"

[[mods]]
    modId="honeynhell"
    version="${version}"
    displayName="Honey 'n' Hell"
    description='''
    Beekeeping and honey production!...With a sinister twist...
    '''

[[dependencies.honeynhell]]
    modId="forge"
    mandatory=true
    versionRange="[24,)"
    ordering="NONE"
    side="BOTH"