modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/Glitchfiend/HoneyAndHell/issues"
displayURL="https://minecraft.curseforge.com/projects/honey-and-hell"
authors="Adubbz, Forstride"

[[mods]]
    modId="honeyandhell"
    version="${version}"
    displayName="Honey & Hell"
    description='''
    Ghastly bees.
    '''

[[dependencies.honeyandhell]]
    modId="forge"
    mandatory=true
    versionRange="[24,)"
    ordering="NONE"
    side="BOTH"